

<br>
<table border="0" cellpadding="3" cellspacing="0">
<tr><td colspan=2><h3>Bray Wanderers Supporters Club:</h3></td></tr>

<tr><td><p>Secretary</td><td><p> Dermot Carey</td></tr>
<tr><td><p>Treasurer</td><td><p> Mick Duffy</td></tr>
<tr><td><p>Telephone:</td><td><p> +353 (87) 996 8969</td></tr>
<tr><td><p>Mail address:</td><td><p>	c/o Bray Wanderers AFC (as above)</td></tr></table>
<BR>

<table border="0" cellpadding="3" cellspacing="0">
<tr><td colspan=2><h3>Further information</h3></td></tr>
<tr><td><p>General information</td><td><p><a href=mailto:bwsc@eircom.net>Mick Duffy<bwsc@eircom.net/a></td></tr>
<tr><td><p>Shop</td><td><p><a href=mailto:bwsc@eircom.net>bwsc@eircom.net</a></td></tr>
<tr><td><p>Press enquiries</td><td><p><a href=mailto:bwsc@eircom.net>bwsc@eircom.net</a></td></tr>
<tr><td><p>Webmaster</td><td><p><a href=mailto:bwsc@eircom.net>bwsc@eircom.net</a></td></tr>
</table>


<p>This site is administered by Bray Wanderers Supporters Club and IS NOT THE OFFICIAL CLUB SITE,


<table border="0" cellpadding="3" cellspacing="0">

<tr><td colspan=2><h3>Bray Wanderers AFC:</h3></td></tr>


<tr><td><p>Chairman </td><td><p>Eddie Slevin</td></tr>
<tr><td><p>Club Secretary </td><td><p>Eddie Slevin</td></tr>
<tr><td><p>Director of Finance </td><td><p>Frank Slevin</td></tr>
<tr><td><p>Director of Football </td><td><p>Eddie Cox</td></tr>
<tr><td><p>General Manager </td><td><p>Jack O'Neill</td></tr>
<tr><td><p>Telephone: </td><td><p>+353 (1) 282 8214</td></tr>
<tr><td valign=top><p>Mail address: </td><td><p>	Carlisle Grounds<br>
		Quinnsboro' Road<br>
		Bray<br>
		County Wicklow<br>
		Republic of Ireland</td></tr></table>

<table border="0" cellpadding="3" cellspacing="0">
<tr><td><p>Email: <b>Administration</b>: <a href="mailto:carlislegrounds@eircom.net">carlislegrounds@eircom.net</a></td></tr>
<tr><td><p>	<b>General Manager</b>: <a href="mailto:jackoneill@braywanderers.ie">jackoneill@braywanderers.ie</a></td></tr></table>

<br>
<i><b>Player enquiries:</b></i><br>All player enquiries, in writing only, with full CV, to the club's postal address above<br>

