<table border="0" cellpadding="3" cellspacing="0">
<tr><td valign="top" width="479" align="left" colspan="3"><p>
<h2>Bray Wanderers AFC</h1>
<h3>Founded 1942</h3>
</td></tr>


<table border="0" cellpadding="3" cellspacing="0">
<tr><td valign="top" width="479" align="left" colspan="3"><p>
<tr><td><p>Address:</td><td><p>Carlisle Grounds</td></tr>
<tr><td><p> </td><td><p>Quinnsborough Rd</td></tr>
<tr><td><p> </td><td><p>Bray</td></tr>
<tr><td><p> </td><td><p>Co Wicklow</td></tr>
<tr><td><p> </td><td><p>Ireland</td></tr>
<tr><td><p>Phone:</td><td><p>[+353] 01 282 8214</td></tr>
<tr><td><p>Fax:</td><td><p>[+353] 01 282 8684</td></tr>
</td></tr>
</table><br><br>

<br>
<p><a href="http://www.braywanderers.com/showarticle.php?id=109"><img src="/image/misc/lotto.gif" alt="Check the Seagulls Lotto results here" align=right><p align=right>Check the Seagulls Lotto Results </p></a><br><br>