<h1>Full Fixture List 2001/02</h1>
<h3><a href="#FCUP">FAI Cup</a> and <a href="#LCUP">League Cup</a> draws will be published here when they are made</h3>


<img src="/img/eircom1.gif"><h2>National League, Premier Division</h2>
<p>(Details from FAI website, amendments incorporated where known. All matches at 7.45 pm unless stated)
<pre>
Series 1
      Thu 9.8.01 Dundalk v UCD, Oriel Park  
      Fri 10.8.01 Bohemians v Derry City, Dalymount Park 
      Fri 10.8.01 St Patrick's Athletic v Galway United, Richmond Park
      Sat 11.8.01 Longford Town v Cork City, Flancare Park 7.30
      Sun 12.8.01 <font color=green>Bray Wanderers</font> v Shamrock Rovers, Carlisle Grnds 3.15
      Sun 12.8.01 Monaghan United v Shelbourne, Gortakeegan 3.00

Series 2
      Thu 16.8.01 Derry City v Monaghan United, Brandywell
      Thu 16.8.01 UCD v Longford Town, Belfield Park 7.30
      Fri 17.8.01 Galway United v <font color=green>Bray Wanderers</font>, Terryland Park
      Fri 17.8.01 Shelbourne v St Patrick's Athletic, Tolka Park
      Sun 19.8.01 Cork City v Bohemians, Turner's Cross 2.00
      Mon 20.8.01 Shamrock Rovers v Dundalk, Tolka Park

Series 3
      Thu 23.8.01 Dundalk  v Shelbourne, Oriel Park
      Fri 24.8.01 Bohemians v UCD, Dalymount Park
      Fri 24.8.01 <font color=green>Bray Wanderers</font> v Cork City, Carlisle Grnds
      Fri 24.8.01 St Patrick's Athletic v Derry City, Richmond Park
      Sat 25.8.01 Longford Town v Shamrock Rovers, Flancare Park 7.30
      Sun 26.8.01 Monaghan United v Galway United, Gortakeegan 3.00

Series 4
      Thu 30.8.01 Derry City v <font color=green>Bray Wanderers</font>, Brandywell
      Thu 30.8.01 UCD v St Patrick's Athletic, Belfield Park 7.30
      Fri 31.8.01 Galway United v Bohemians, Terryland Park
      Fri 31.8.01 Shelbourne v Longford Town, Tolka Park
      Sun 2.9.01 Cork City v Dundalk, Turner's Cross 2.00
      Mon 3.9.01 Shamrock Rovers v Monaghan United, Tolka Park

Series 5
      Thu 6.9.01 Dundalk v Galway United, Oriel Park
      Fri 7.9.01 Bohemians v Shamrock Rovers, Dalymount Park 
      Fri 7.9.01 St Patrick's Athletic v Cork City, Richmond Park 
      Sat 8.9.01 Longford Town v Derry City, Flancare Park 7.30
      Sun 9.9.01 <font color=green>Bray Wanderers</font> v Shelbourne, Carlisle Grnds 3.15
      Sun 9.9.01 Monaghan United v UCD, Gortakeegan 3.00

Series 6
      Thu 13.9.01 UCD v Galway United, Belfield Park 7.30
      Thu 13.9.01 Derry City v Shamrock Rovers, Brandywell
      Fri 14.9.01 Bohemians v Monaghan United, Dalymount Park
      Fri 14.9.01 St Patrick's Athletic v <font color=green>Bray Wanderers</font>, Richmond Park
      Sat 15.9.01 Longford Town v Dundalk, Flancare Park 7.30
      Sun 16.9.01 Cork City v Shelbourne, Turner's Cross 2.00

Series 7
      Tue 18.9.01 <font color=green>Bray Wanderers</font> v Longford Town, Carlisle Grnds
      Tue 18.9.01 Dundalk v Bohemians, Oriel Park
      Tue 18.9.01 Monaghan Utd v St Patrick's Ath, Gortakeegan 7.30
      Tue/Wed 18/19.9.01 Galway United v Cork City, Terryland Park
      Tue/Wed 18/19.9.01 Shamrock Rovers v UCD, Tolka Park
      Tue/Wed 18/19.9.01 Shelbourne v Derry City, Tolka Park

Series 8
      Thu 20.9.01 Derry City v UCD, Brandywell
      Fri 21.9.01 <font color=green>Bray Wanderers</font> v Dundalk, Carlisle Grnds
      Fri 21.9.01 St Patrick's Athletic v Bohemians, Richmond Park
      Fri 21.9.01 Shelbourne v Galway United, Tolka Park
      Sat 22.9.01 Longford Town v Monaghan U, Flancare Park 7.30
      Sun 23.9.01 Cork City v Shamrock Rovers, Turner's Cross 2.00

Series 9
      Mon 24.9.01 Dundalk v St Patrick's Athletic, Oriel Park
      Tue 25.9.01 Bohemians v Longford Town, Dalymount Park
      Tue 25.9.01 Monaghan Utd v <font color=green>Bray Wanderers</font>, Gortakeegan 7.30
      Tue/Wed 25/26.9.01 Galway United v Derry City, Terryland Park
      Tue/Wed 25/26.9.01 Shamrock Rovers v Shelbourne, Tolka Park
      Tue/Wed 25/26.9.01 UCD v Cork City, Belfield Park

Series 10
      Thu 27.9.01 Dundalk v Derry City, Oriel Park
      Fri 28.9.01 Galway United v Longford Town, Terryland Park
      Fri 28.9.01 Shelbourne v UCD, Tolka Park
      Sun 30.9.01 <font color=green>Bray Wanderers</font> v Bohemians, Carlisle Grnds 3.15
      Sun 29.9.01 Cork City v Monaghan United, Turner's Cross 2.00
      Sun 29.9.01 St Patrick's Ath v Shamrock Rovers, Richmond Park 3.00

Series 11
      Thu 4.10.01 Derry City v Cork City, Brandywell
      Thu 4.10.01 UCD v <font color=green>Bray Wanderers</font>, Belfield Park
      Fri 5.10.01 Bohemians v Shelbourne, Dalymount Park
      Sat 6.10.01 Longford Town v St Patrick's Ath, Flancare Park 7.30
      Sun 7.10.01 Monaghan United v Dundalk, Gortakeegan 3.00
      Mon 8.10.01 Shamrock Rovers v Galway United, Tolka Park

Series 12
      Thu 11.10.01 Derry City v Bohemians, Brandywell
      Thu 11.10.01 UCD v Dundalk, Belfield Park
      Fri 12.10.01 Galway United v St Patrick's Athletic, Terryland Park
      Fri 12.10.01 Shelbourne v Monaghan United, Tolka Park
      Sun 14.10.01 Cork City v Longford Town, Turner's Cross 2.00
      Sun 14.10.01 Shamrock Rovers v <font color=green>Bray Wanderers</font>, Tallaght 3.15

Series 13
      Thu 18.10.01 Dundalk v Shamrock Rovers, Oriel Park
      Fri 19.10.01 Bohemians v Cork City, Dalymount Park
      Fri 19.10.01 <font color=green>Bray Wanderers</font> v Galway United, Carlisle Grnds
      Fri 19.10.01 St Patrick's Athletic v Shelbourne, Richmond Park
      Sat 20.10.01 Longford Town v UCD, Flancare Park 7.30
      Sun 21.10.01 Monaghan United v Derry City, Gortakeegan 3.00

Series 14
      Thu 25.10.01 Derry City v St Patrick's Athletic, Brandywell
      Thu 25.10.01 UCD v Bohemians, Belfield Park
      Fri 26.10.01 Galway United v Monaghan United, Terryland Park
      Fri 26.10.01 Shelbourne v Dundalk, Tolka Park
      Sun 28.10.01 Cork City v <font color=green>Bray Wanderer</font>, Turner's Cross 2.00
      Sun 28.10.01 Shamrock Rovers v Longford Town, Tallaght 3.15

Series 15
      Thu 1.11.01 Dundalk v Cork City, Oriel Park
      Fri 2.11.01 Bohemians v Galway United, Dalymount Park
      Fri 2.11.01 <font color=green>Bray Wanderers</font> v Derry City, Carlisle Grnds
      Fri 2.11.01 St Patrick's Athletic v UCD, Richmond Park
      Sat 3.11.01 Longford Town v Shelbourne, Flancare Park 7.30
      Sun 4.11.01 Monaghan United v Shamrock R, Gortakeegan 3.00

Series 16
      Thu 8.11.01 Derry City v Longford Town, Brandywell
      Thu 8.11.01 UCD v Monaghan United, Belfield Park
      Fri 9.11.01 Galway United v Dundalk, Terryland Park
      Fri 9.11.01 Shelbourne v <font color=green>Bray Wanderers</font>, Tolka Park
      Sun 11.11.01 Cork City v St Patrick's Athletic, Turner's Cross 2.00
      Sun 11.11.01 Shamrock Rovers v Bohemians, Tallaght 3.15

Series 17
      Thu 15.11.01 Dundalk v Longford Town, Oriel Park
      Fri 16.11.01 Galway United v UCD, Terryland Park
      Fri 16.11.01 Shelbourne v Cork City, Tolka Park
      Sun 18.11.01 <font color=green>Bray Wanderers</font> v St Patrick's Athletic, Carlisle Grnds 3.15
      Sun 18.11.01 Monaghan United v Bohemians, Gortakeegan 3.00
      Sun 18.11.01 Shamrock Rovers v Derry City, Tallaght 3.15

Series 18
      Thu 22.11.01 Derry City v Shelbourne, Brandywell
      Thu 22.11.01 UCD v Shamrock Rovers, Belfield Park
      Fri 23.11.01 Bohemians v Dundalk, Dalymount Park
      Fri 23.11.01 St Patrick's Athletic v Monaghan U, Richmond Park
      Sat 24.11.01 Longford Town v <font color=green>Bray Wanderers</font>, Flancare Park 7.30
      Sun 25.11.01 Cork City v Galway United, Turner's Cross 2.00

Series 19
      Thu 29.11.01 Dundalk v <font color=green>Bray Wanderers</font>, Oriel Park
      Thu 29.11.01 UCD v Derry City, Belfield Park
      Fri 30.11.01 Bohemians v St Patrick's Athletic, Dalymount Park
      Fri 30.11.01 Galway United v Shelbourne, Terryland Park
      Sun 2.12.01 Monaghan United v Longford Town, Gortakeegan 3.00
      Sun 2.12.01 Shamrock Rovers v Cork City, Tallaght 3.15

Series 20
      Thu 6.12.01 Derry City v Galway United, Brandywell
      Fri 7.12.01 <font color=green>Bray Wanderers</font> v Monaghan United, Carlisle Grnds
      Fri 7.12.01 St Patrick's Athletic v Dundalk, Richmond Park
      Fri 7.12.01 Shelbourne v Shamrock Rovers, Tolka Park
      Sat 8.12.01 Longford Town v Bohemians, Flancare Park 7.30
      Sun 9.12.01 Cork City v UCD, Turner's Cross 2.00

Series 21
      Thu 20.12.01 Derry City v Dundalk, Brandywell
      Thu 20.12.01 UCD v Shelbourne, Belfield Park
      Fri 21.12.01 Bohemians v <font color=green>Bray Wanderers</font>, Dalymount Park
      Sat 22.12.01 Longford Town v Galway United, Flancare Park 7.30
      Sun 23.12.01 Monaghan United v Cork City, Gortakeegan 3.00
      Sun 23.12.01 Shamrock Rovers v St Patrick's Ath, Tallaght 3.15

Series 22
      Thu 27.12.01 Dundalk v Monaghan United, Oriel Park
      Fri 28.12.01 <font color=green>Bray Wanderers</font> v UCD, Carlisle Grnds
      Fri 28.12.01 Galway United v Shamrock Rovers, Terryland Park
      Fri 28.12.01 St Patrick's Athletic v Longford Town, Richmond Park
      Fri 28.12.01 Shelbourne v Bohemians, Tolka Park
      Sun 30.12.01 Cork City v Derry City, Turner's Cross 2.00

Series 23
      Thu 3.1.02 Dundalk v UCD, Oriel Park
      Fri 4.1.02 Bohemians v Derry City, Dalymount Park
      Fri 4.1.02 St Patrick's Athletic v Galway United, Richmond Park
      Sat 5.1.02 Longford Town v Cork City, Flancare Park 7.30
      Sun 6.1.02 <font color=green>Bray Wanderers</font> v Shamrock Rovers, Carlisle Grnds 3.15
      Sun 6.1.02 Monaghan United v Shelbourne, Gortakeegan 3.00

Series 24
      Thu 17.1.02 Derry City v Monaghan United, Brandywell
      Thu 17.1.02 UCD v Longford Town, Belfield Park
      Fri 18.1.02 Galway United v <font color=green>Bray Wanderers</font>, Terryland Park
      Fri 18.1.02 Shelbourne v St Patrick's Athletic, Tolka Park
      Sun 20.1.02 Cork City v Bohemians, Turner's Cross 2.00
      Sun 20.1.02 Shamrock Rovers v Dundalk, Tallaght 3.15

Series 25
      Thu 24.1.02 Dundalk v Shelbourne, Oriel Park
      Fri 25.1.02 Bohemians v UCD, Dalymount Park
      Fri 25.1.02 <font color=green>Bray Wanderers</font> v Cork City, Carlisle Grnds
      Fri 25.1.02 St Patrick's Athletic v Derry City, Richmond Park
      Sat 26.1.02 Longford Town v Shamrock Rovers, Flancare Park 7.30
      Sun 27.1.02 Monaghan United v Galway United, Gortakeegan 3.00

Series 26
      Thu 31.1.02 Derry City v <font color=green>Bray Wanderers</font>, Brandywell
      Thu 31.1.02 UCD v St Patrick's Athletic, Belfield Park
      Fri 1.2.02 Galway United v Bohemians, Terryland Park
      Fri 1.2.02 Shelbourne v Longford Town, Tolka Park
      Sun 3.2.02 Cork City v Dundalk, Turner's Cross 2.00
      Sun 3.2.02 Shamrock Rovers v Monaghan United, Tallaght 3.15

Series 27
      Thu 14.2.02 Dundalk v Galway United, Oriel Park
      Fri 15.2.02 Bohemians v Shamrock Rovers, Dalymount Park
      Fri 15.2.02 St Patrick's Athletic v Cork City, Richmond Park
      Sat 16.2.02 Longford Town v Derry City, Flancare Park 7.30
      Sun 17.2.02 <font color=green>Bray Wanderers</font> v Shelbourne, Carlisle Grnds 3.15
      Sun 17.2.02 Monaghan United v UCD, Gortakeegan 3.00

Series 28
      Thu 21.2.02 Derry City v Shamrock Rovers, Brandywell
      Fri 22.2.02 UCD v Galway United, Belfield Park
      Fri 22.2.02 Bohemians v Monaghan United, Dalymount Park
      Fri 22.2.02 St Patrick's Ath v <font color=green>Bray Wanderers</font>, Richmond Park
      Sat 23.2.02 Longford Town v Dundalk, Flancare Park 7.30
      Sun 24.2.02 Cork City v Shelbourne, Turner's Cross 2.00

Series 29
      Thu 28.2.02 Dundalk v Bohemians, Oriel Park
      Fri 1.3.02 <font color=green>Bray Wanderers</font> v Longford Town, Carlisle Grnds
      Fri 1.3.02 Galway United v Cork City, Terryland Park
      Fri 1.3.02 Shelbourne v Derry City, Tolka Park
      Sun 3.3.02 Monaghan Utd v St Patrick's Ath, Gortakeegan 3.00
      Sun 3.3.02 Shamrock Rovers v UCD, Tallaght 3.15

Series 30
      Thu 7.3.02 Derry City v UCD, Brandywell
      Fri 8.3.02 <font color=green>Bray Wanderers</font> v Dundalk, Carlisle Grnds
      Fri 8.3.02 St Patrick's Athletic v Bohemians, Richmond Park
      Fri 8.3.02 Shelbourne v Galway United, Tolka Park
      Sat 9.3.02 Longford Town v Monaghan Utd, Flancare Park 7.30
      Sun 10.3.02 Cork City v Shamrock Rovers, Turner's Cross 2.00

Series 31
      Thu 14.3.02 Dundalk v St Patrick's Athletic, Oriel Park
      Thu 14.3.02 UCD v Cork City, Belfield Park
      Fri 15.3.02 Bohemians v Longford Town, Dalymount Park
      Fri 15.3.02 Galway United v Derry City, Terryland Park
      Sun 17.3.02 Monaghan Utd v <font color=green>Bray Wanderers</font>, Gortakeegan 3.00
      Sun 17.3.02 Shamrock Rovers v Shelbourne, Tallaght 3.15

Series 32
      Thu 21.3.02 Dundalk v Derry City, Oriel Park
      Fri 22.3.02 Galway United v Longford Town, Terryland Park
      Fri 22.3.02 St Patrick's Ath v Shamrock Rovers, Richmond Park
      Fri 22.3.02 Shelbourne v UCD, Tolka Park
      Sun 24.3.02 <font color=green>Bray Wanderers</font> v Bohemians, Carlisle Grnds 3.15
      Sun 24.3.02 Cork City v Monaghan United, Turner's Cross 2.00

Series 33
      Thu 28.3.02 Derry City v Cork City, Brandywell
      Thu 28.3.02 UCD v <font color=green>Bray Wanderers</font>, Belfield Park
      Fri 29.3.02 Bohemians v Shelbourne, Dalymount Park
      Sat 30.3.02 Longford Town v St Patrick's Ath, Flancare Park 7.30
      Sun 31.3.02 Monaghan United v Dundalk, Gortakeegan 3.00
      Sun 31.3.02 Shamrock Rovers v Galway United, Tallaght 3.15
</pre>

<hr size=2 width=50%>

<img src="/image/logos/harp.jpg" align=right><h2><a name="FCUP">FAI Cup</a></h2>

<p>Weekending Sunday, December 16<br>Second Round
Weekending Sunday, January 13<br>Third Round
Weekending Sunday, February 10<br>Quarter-finals
Weekending Sunday, March 10<br>Semi-finals
Weekending Sunday, April 7<br>Cup Final

<hr size=2 width=50%>

<img src="/img/fai.gif" align=left></p>
<p align=right><h2><a name="LCUP">League Cup</a></h2>
<h3>First Round</h3>

Bohemians V Dublin City
<font color=green>Bray Wanderers</font> V UCD
Drogheda United V Dundalk
St Francis V St Patricks Athletic
Shelbourne V Shamrock Rovers
Cobh Ramblers V Cork City
Waterford United V Kilkenny City
Sligo Rovers V Monaghan United
Finn Harps V Derry City
Galway United V Limerick
Longford Town V Athlone Town
<I>If ties finish level, extra time and penalties will apply.</I>