<h2>Bray Wanderers Supporters Club Shop</h2>
<p><img src="/image/logos/fiacla-sm.gif" alt="Fiacla: sponsoring the Supporters Club Shop" height=30>


<img src="/image/shop/Kit3.jpg" width=250 align=right><br><p><p align=right><i>New kit! Tarzan at home, Flood away, Frank Slevin keeping the peace!!</I>
<p>
<h3>Departments under construction</h3>
<a href="http://www.braywanderers.ie/showarticle.php?id=497"><h4>Replica Strips</h4></a>
<a href="http://www.braywanderers.ie/showarticle.php?id=497"><h4>Leisurewear</h4></a>
<a href="http://www.braywanderers.ie/showarticle.php?id=497"><h4>Souvenirs</h4><br></a>
<a href="http://www.braywanderers.ie/showarticle.php?id=497"><h4>Publications</h4></a>													
<h2>Price List</h2>
<Table border=0 width=479 font size=-1>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New"><B>Replica Strips - <I>ADULTS SIZES ONLY</I>
</B></FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New"><b>&euro;</b></FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Home Jersey</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">40.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Away Jersey</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">50.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New"><B>Baby wear</B></FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">&nbsp;</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Bibs</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">6.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Babygrows</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">10.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New"><B>Childrens wear</B></FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">&nbsp;</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Bray Wanderers jackets Navy with crest (made to order)</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">50.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Bray Wanderers jackets Red with crest (made to order)</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">50.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Bray Wanderers T-Shirts</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">10.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New"><B>Leisurewear Adults</B></FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">&nbsp;</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Replica Bray Wanderers Adidas Drill tops</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">35.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Jackets (navy and cream/with crest) (made to order)</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">100.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Sweatshirt Navy with crest</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">23.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Polo Shirts Navy with crest</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">23.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Fleeces Dark Grey with crest</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">45.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New"><B>Souvenirs</B></FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">&nbsp;</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">New Seagulls scarf (2003)</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">10.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Wool ski hat (embroidered crest)</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">10.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Baseball hat Navy with crest</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">12.50</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Umbrella</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">19.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Junior kitbag</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">12.50</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Pennants</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">10.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Metal Badge</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">3.50</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Key Ring</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">2.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">CD Holder</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">6.25</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Mug</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">5.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Golf balls (crested) Dunlop, sleeve of 3</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">9.50</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">                             box of 15</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">40.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Golf Balls (crested) Titleist, sleeve of 3</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">10.75</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">                               box of 12</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">45.50</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New"><B>Publications</B></FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">&nbsp;</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Programmes - cover prices (old and new) prices from </FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">2.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New"><I>Tales of the Wanderers</I></FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">6.50</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New"><I>More Tales of the Wanderers</I></FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">6.50</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">CD <I>Red Rose Caf&eacute;</I></FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">3.50</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New"><I>Sing when You're Losing</I></FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">6.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">Photos: Player (Autographed) (A4)</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">2.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">        Player (laminated)</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">4.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">        Team (Home/Away) (A3)</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">2.00</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="Courier New">        Team (laminated)</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:_(* #,##0.00_)[semicolon]_(* (#,##0.00)[semicolon]_(* [dquote]-[dquote]??_)[semicolon]_(@_)"><FONT FACE="Courier New">5.00</FONT></TD>
</TR>
</Table>
<a href="http://www.braywanderers.ie/showarticle.php?id=497"><h4>Order Form</h4></a> available shortly<p>

The Shop area is under development.

<img src="/shopint.jpg" alt="The Supporters Club Shop: Come in and see us sometime!" border=0><br>