<table width=482>
<tr><td>
<p>
This site is administered by Bray Wanderers Supporters Club<br>
All News text is &copy copyright Bray Wanderers Supporters Club.<br>
All other text is &copy copyright the authors or, where another source is
acknowledged, the original publisher or author as credited.<br>
All photos are &copy copyright Michael Tierney, except where otherwise indicated.
<p>
Bray Wanderers Supporters Club takes no responsibility for opinions expressed by the authors of signed material on this site.
<p>
The site is hosted by <a href=http://www.enom.com/>Enom.com<!-- <img
src=img/netsource.jpg border=0 align=right>--></a>	
<p>
Site design by <a href=mailto:cmelia@musign.com>Ciaran Melia</a>.<br>
Content design by the BWSC web team.
<p>
Technical enquiries to the Webmaster, <a
href=mailto:braywanderers@eircom.net>Mark O'Neill/Mick Duffy/Thomas Bridge.</a>
<p>
Editorial enquiries to the Editor, <a href=mailto:bwsc@eircom.net>Míck Duffy</a>
</td></tr></table>

<h3>Virus information from <a href="http://www.sophos.com">Sophos</a></h3>

<table width=482><tr><td>
<!-- Sophos info feed: latest virus alerts - START -->
<script language="JavaScript1.1"
src="http://www.sophos.com/virusinfo/infofeed/tenalerts.js"></script>
<script language="JavaScript1.1"><!--
// Want to customise the look and feel of the virus information
// on your site? Simply change the following values to your own// preferences.//
// Changing the value of 'count' will change the number of rows// displayed.
// Changing the value of 'target' to 'new' will display the link in 
// a new window.
// *****************************************************************
var bgcolour_main     = '#cccccc'var bgcolour_heading  = '#99cccc'
var text_colour       = '#000000'var link_colour       = '#000099'
var font_size         = '1'
var font_face         = 'verdana, arial, helvetica, sans-serif'
var count             =  10   // number should be between 1 and 10
var first_column      = 'yes' // 'yes' or 'no'
var cellspacing       = 'yes' // 'yes' or 'no'
var target            = '_self' // '_self' or 'new'
// *****************************************************************
//  Be careful not to change anything below this line!var htmltxt = "";
var font_desc = '<font face="' + font_face + '" size="'
  + font_size + '" color="' + text_colour + '">';var tmp_count = 0;    
if (first_column == "no") {   colspan = 1;} else {  colspan = 2;}
if (cellspacing == "no") {   cellspacing = 0;} else {  cellspacing = 2;}  
if (count > 0) {  if (count > 10) {count = 10}
  htmltxt += '\n<table cellpadding="6" cellspacing="' 
  + cellspacing + '" border="0" bgcolor="#ffffff">';  if (count == 1) {
    htmltxt += '\n<tr><td colspan="' + colspan + '" bgcolor="'
    + bgcolour_heading + '">' + font_desc 
    + '<b>Latest virus alert</b></font></td></tr>';  } else { 
    htmltxt += '\n<tr><td colspan="' + colspan + '" bgcolor="'
    + bgcolour_heading + '">' + font_desc + '<b>Latest ' 
    + count + ' virus alerts</b></font></td></tr>';  }
  for (var i=0; i<tenalerts.length; i+=3) {    tmp_count++;
    if (tmp_count > count) {      break;    } else {
      if (first_column == "no") {
        htmltxt += '\n<tr><td bgcolor="' + bgcolour_main + '">' 
        + font_desc + '<a href="' + tenalerts[i+2] + '" target="' 
        + target + '"><font color="'
        + link_colour + '"><nobr>' + tenalerts[i+1]
        + '</nobr></font></a></font></td></tr>';      } else {  
        htmltxt += '\n<tr><td bgcolor="' + bgcolour_main + '">' 
        + font_desc + '<nobr>' + tenalerts[i+0] 
        + '</nobr></font></td><td bgcolor="' + bgcolour_main + '">' 
        + font_desc + '<a href="' + tenalerts[i+2] + '" target="' 
        + target + '"><font color="'
        + link_colour + '"><nobr>' + tenalerts[i+1]
        + '</nobr></font></a></font></td></tr>';      }    }    }} else {
  document.write
  ("=== Sophos info feed error: Specify value of count > 0 ===");}
htmltxt += '\n<tr><td colspan="' + colspan + '" bgcolor="'
+ bgcolour_heading + '">' + font_desc 
+ 'Source: <a href="http://www.sophos.com" target="' 
+ target + '"><font color="' + link_colour 
+ '">Sophos Anti-Virus</font></a></font></td></tr>';
htmltxt += '\n<tr><td colspan="' + colspan + '" bgcolor="'
+ bgcolour_heading + '">' + font_desc 
+ '<a href="http://www.sophos.com/virusinfo/infofeed/" target="' 
+ target + '"><font color="' + link_colour 
+ '">Add this info to your website</font></a></font></td></tr>';
htmltxt += '\n</table>';document.write(htmltxt);//--></script>
<!-- Sophos info feed: latest virus alerts - END --><!-- Sophos info feed: latest virus alerts - START -->
<script language="JavaScript1.1"
src="http://www.sophos.com/virusinfo/infofeed/tenalerts.js"></script>
<script language="JavaScript1.1"><!--
// Want to customise the look and feel of the virus information
// on your site? Simply change the following values to your own// preferences.//
// Changing the value of 'count' will change the number of rows// displayed.
// Changing the value of 'target' to 'new' will display the link in 
// a new window.
// *****************************************************************
var bgcolour_main     = '#cccccc'var bgcolour_heading  = '#99cccc'
var text_colour       = '#000000'var link_colour       = '#000099'
var font_size         = '1'
var font_face         = 'verdana, arial, helvetica, sans-serif'
var count             =  10   // number should be between 1 and 10
var first_column      = 'yes' // 'yes' or 'no'
var cellspacing       = 'yes' // 'yes' or 'no'
var target            = '_self' // '_self' or 'new'
// *****************************************************************
//  Be careful not to change anything below this line!var htmltxt = "";
var font_desc = '<font face="' + font_face + '" size="'
  + font_size + '" color="' + text_colour + '">';var tmp_count = 0;    
if (first_column == "no") {   colspan = 1;} else {  colspan = 2;}
if (cellspacing == "no") {   cellspacing = 0;} else {  cellspacing = 2;}  
if (count > 0) {  if (count > 10) {count = 10}
  htmltxt += '\n<table cellpadding="6" cellspacing="' 
  + cellspacing + '" border="0" bgcolor="#ffffff">';  if (count == 1) {
    htmltxt += '\n<tr><td colspan="' + colspan + '" bgcolor="'
    + bgcolour_heading + '">' + font_desc 
    + '<b>Latest virus alert</b></font></td></tr>';  } else { 
    htmltxt += '\n<tr><td colspan="' + colspan + '" bgcolor="'
    + bgcolour_heading + '">' + font_desc + '<b>Latest ' 
    + count + ' virus alerts</b></font></td></tr>';  }
  for (var i=0; i<tenalerts.length; i+=3) {    tmp_count++;
    if (tmp_count > count) {      break;    } else {
      if (first_column == "no") {
        htmltxt += '\n<tr><td bgcolor="' + bgcolour_main + '">' 
        + font_desc + '<a href="' + tenalerts[i+2] + '" target="' 
        + target + '"><font color="'
        + link_colour + '"><nobr>' + tenalerts[i+1]
        + '</nobr></font></a></font></td></tr>';      } else {  
        htmltxt += '\n<tr><td bgcolor="' + bgcolour_main + '">' 
        + font_desc + '<nobr>' + tenalerts[i+0] 
        + '</nobr></font></td><td bgcolor="' + bgcolour_main + '">' 
        + font_desc + '<a href="' + tenalerts[i+2] + '" target="' 
        + target + '"><font color="'
        + link_colour + '"><nobr>' + tenalerts[i+1]
        + '</nobr></font></a></font></td></tr>';      }    }    }} else {
  document.write
  ("=== Sophos info feed error: Specify value of count > 0 ===");}
htmltxt += '\n<tr><td colspan="' + colspan + '" bgcolor="'
+ bgcolour_heading + '">' + font_desc 
+ 'Source: <a href="http://www.sophos.com" target="' 
+ target + '"><font color="' + link_colour 
+ '">Sophos Anti-Virus</font></a></font></td></tr>';
htmltxt += '\n<tr><td colspan="' + colspan + '" bgcolor="'
+ bgcolour_heading + '">' + font_desc 
+ '<a href="http://www.sophos.com/virusinfo/infofeed/" target="' 
+ target + '"><font color="' + link_colour 
+ '">Add this info to your website</font></a></font></td></tr>';
htmltxt += '\n</table>';document.write(htmltxt);//--></script>
<!-- Sophos info feed: latest virus alerts - END -->



<!-- Sophos info feed: top virus hoaxes - START -->
<script language="JavaScript1.1"
src="http://www.sophos.com/virusinfo/infofeed/hoax.js"></script>
<script language="JavaScript1.1">
<!--

// Want to customise the look and feel of the virus information
// on your site? Simply change the following values to your own
// preferences.
//
// Changing the value of 'count' will change the number of rows
// displayed.
// Changing the value of 'target' to 'new' will display the link in
// a new window.

// *****************************************************************

var bgcolour_main     = '#cccccc'
var bgcolour_heading  = '#99cccc'
var text_colour       = '#000000'
var link_colour       = '#000099'
var font_size         = '1'
var font_face         = 'verdana, arial, helvetica, sans-serif'
var count             =  10   // number should be between 1 and 10
var first_column      = 'yes' // 'yes' or 'no'
var cellspacing       = 'yes' // 'yes' or 'no'
var target            = '_self' // '_self' or 'new'

// *****************************************************************
//  Be careful not to change anything below this line!


var htmltxt = "";
var font_desc = '<font face="' + font_face + '" size="'
  + font_size + '" color="' + text_colour + '">';
var tmp_count = 0;

if (first_column == "no") {
  colspan = 1;
} else {
  colspan = 2;
}

if (cellspacing == "no") {
  cellspacing = 0;
} else {
  cellspacing = 2;
}

if (count > 0) {
  if (count > 10) {count = 10}
  htmltxt += '\n<table cellpadding="6" cellspacing="'
  + cellspacing + '" border="0" bgcolor="#ffffff">';
  if (count == 1) {
    htmltxt += '\n<tr><td colspan="' + colspan + '" bgcolor="'
    + bgcolour_heading + '">' + font_desc
    + '<b>Top virus hoax</b></font></td></tr>';
  } else {
    htmltxt += '\n<tr><td colspan="' + colspan + '" bgcolor="'
    + bgcolour_heading + '">' + font_desc + '<b>Top '
    + count + ' virus hoaxes</b></font></td></tr>';
  }

  for (var i=0; i<hoax.length; i+=3) {
    tmp_count++;
    if (tmp_count > count) {
      break;
    } else {
      if (first_column == "no") {
        htmltxt += '\n<tr><td bgcolor="' + bgcolour_main + '">'
        + font_desc + '<a href="' + hoax[i+2] + '" target="'
        + target + '"><font color="'
        + link_colour + '"><nobr>' + hoax[i+1]
        + '</nobr></font></a></font></td></tr>';
      } else {
        htmltxt += '\n<tr><td bgcolor="' + bgcolour_main + '">'
        + font_desc + '<nobr>' + hoax[i+0]
        + '</nobr></font></td><td bgcolor="' + bgcolour_main + '">'
        + font_desc + '<a href="' + hoax[i+2] + '" target="'
        + target + '"><font color="'
        + link_colour + '"><nobr>' + hoax[i+1]
        + '</nobr></font></a></font></td></tr>';
      }
    }
  }
} else {
  document.write
  ("=== Sophos info feed error: Specify value of count > 0 ===");
}


htmltxt += '\n</table>';

document.write(htmltxt);
//-->
</script>
<!-- Sophos info feed: top virus hoaxes - END -->
</td></tr></table>
