<h1>Supporters Club</h1>
<img src="/Supporters Logo.jpg" align=right width=250><p align=right><i>

<a href="/showarticle.php?id=456">Supporters Club Constitution</a>


<h3>Aims and Objectives</h3>
<p>
The Supporters Club was established formally in 1985.
<p>
Its objectives - apart from bringing active supporters together socially - are to support Bray Wanderers Ltd in any appropriate way, or as requested by the football club.
<p>
The Club has a formal Constitution, and elects Officers and Committee annually at its Annual General Meeting.
<p>
Among the Club's regular activities are arranging transport to away matches; producing the matchday programme on behalf of the AFC; administering this website on behalf of the football club; running the souvenir shop in the Carlisle Grounds (a subcommittee of the Supporters Club is in charge of this); fundraising; and arranging social events.
<p>
Supporters Club activists are also often requested to assist the AFC on matchdays, whether by staffing turnstiles, providing additional stewarding, or selling halftime draw tickets and programmes.

<h3>Committee 2015 Season</h3>
<p>Chairperson: Terry O'Neill<br>Secretary: Frank Quinn<br>Treasurer: Michael Duffy<br>PRO: Padraig Moran<br>Supporters Liasion Officer: Ross McGovern<br>Trustees: Declan Crinion & Charlie Kavanagh